-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 10:18:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`user` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`user` (
  `user_email` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL DEFAULT 'USER',
  `user_name` VARCHAR(45) NOT NULL,
  `user_pw` VARCHAR(255) NOT NULL,
  `user_phone` VARCHAR(45) NULL,
  `user_gender` VARCHAR(1) NULL DEFAULT 'M',
  `user_birth` DATETIME NULL,
  `confirmFile` VARCHAR(255) NULL,
  `writeBoardCount` INT NULL DEFAULT 0,
  `writeCommentCount` INT NULL DEFAULT 0,
  `likesBoardCount` INT NULL DEFAULT 0,
  `isMember` VARCHAR(1) NULL DEFAULT 'Y',
  PRIMARY KEY (`user_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`field` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`field` (
  `field_num` INT NOT NULL AUTO_INCREMENT,
  `field_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`field_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`inquiry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`inquiry` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`inquiry` (
  `inquiry_num` INT NOT NULL AUTO_INCREMENT,
  `inquiry_title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`inquiry_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`confirm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`confirm` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`confirm` (
  `confirm_num` INT NOT NULL AUTO_INCREMENT,
  `confirm_user_email` VARCHAR(45) NOT NULL,
  `sendingTime` DATETIME NOT NULL,
  `isConfirm` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `sendingNum` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`confirm_num`),
  INDEX `user_email_idx` (`confirm_user_email` ASC) VISIBLE,
  CONSTRAINT `comfirm_user_email`
    FOREIGN KEY (`confirm_user_email`)
    REFERENCES `portfolio`.`user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`board` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`board` (
  `board_num` INT NOT NULL AUTO_INCREMENT,
  `board_user_email` VARCHAR(45) NOT NULL,
  `board_type` VARCHAR(45) NOT NULL,
  `board_title` VARCHAR(100) NOT NULL,
  `board_contents` LONGTEXT NOT NULL,
  `registrationDate` DATETIME NOT NULL DEFAULT now(),
  `commentsCount` INT NOT NULL DEFAULT 0,
  `viewsCount` INT NOT NULL DEFAULT 0,
  `likesCount` INT NOT NULL DEFAULT 0,
  `display` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `board_subtype` VARCHAR(45) NOT NULL,
  `answer` VARCHAR(1) NULL,
  `board_field_num` INT NULL,
  `board_inquiry_num` INT NULL,
  PRIMARY KEY (`board_num`),
  INDEX `user_email_idx` (`board_user_email` ASC) VISIBLE,
  INDEX `field_num_idx` (`board_field_num` ASC) VISIBLE,
  INDEX `inquiry_num_idx` (`board_inquiry_num` ASC) VISIBLE,
  CONSTRAINT `board_user_email`
    FOREIGN KEY (`board_user_email`)
    REFERENCES `portfolio`.`user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `board_field_num`
    FOREIGN KEY (`board_field_num`)
    REFERENCES `portfolio`.`field` (`field_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `board_inquiry_num`
    FOREIGN KEY (`board_inquiry_num`)
    REFERENCES `portfolio`.`inquiry` (`inquiry_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`vsType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`vsType` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`vsType` (
  `vsType_num` INT NOT NULL AUTO_INCREMENT,
  `vsType_board_num` INT NOT NULL,
  `yORn` VARCHAR(1) NOT NULL,
  `vsContents` VARCHAR(100) NOT NULL DEFAULT ' ',
  `deadline` DATETIME NOT NULL,
  PRIMARY KEY (`vsType_num`),
  INDEX `board_num_idx` (`vsType_board_num` ASC) VISIBLE,
  CONSTRAINT `vsType_board_num`
    FOREIGN KEY (`vsType_board_num`)
    REFERENCES `portfolio`.`board` (`board_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`surveyType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`surveyType` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`surveyType` (
  `surveyType_num` INT NOT NULL AUTO_INCREMENT,
  `surveyType_board_num` INT NOT NULL,
  `questionType` VARCHAR(45) NOT NULL,
  `isEssential` VARCHAR(1) NOT NULL,
  `surveyContents` VARCHAR(100) NOT NULL,
  `deadline` DATETIME NOT NULL,
  `depth` INT NOT NULL,
  `parentsQ` INT NOT NULL,
  PRIMARY KEY (`surveyType_num`),
  INDEX `board_num_idx` (`surveyType_board_num` ASC) VISIBLE,
  CONSTRAINT `survey_board_num`
    FOREIGN KEY (`surveyType_board_num`)
    REFERENCES `portfolio`.`board` (`board_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`participation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`participation` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`participation` (
  `participation_num` INT NOT NULL AUTO_INCREMENT,
  `participation_user_email` VARCHAR(45) NOT NULL,
  `board_subtype` VARCHAR(45) NOT NULL,
  `participation_vsType_num` INT NULL DEFAULT 0,
  `participation_surveyType_num` INT NULL DEFAULT 0,
  PRIMARY KEY (`participation_num`),
  INDEX `user_email_idx` (`participation_user_email` ASC) VISIBLE,
  INDEX `vsType_num_idx` (`participation_vsType_num` ASC) VISIBLE,
  INDEX `surveyType_num_idx` (`participation_surveyType_num` ASC) VISIBLE,
  CONSTRAINT `participation_user_email`
    FOREIGN KEY (`participation_user_email`)
    REFERENCES `portfolio`.`user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participation_vsType_num`
    FOREIGN KEY (`participation_vsType_num`)
    REFERENCES `portfolio`.`vsType` (`vsType_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participation_surveyType_num`
    FOREIGN KEY (`participation_surveyType_num`)
    REFERENCES `portfolio`.`surveyType` (`surveyType_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`like` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`like` (
  `like_num` INT NOT NULL AUTO_INCREMENT,
  `like_board_num` INT NOT NULL,
  `like_user_email` VARCHAR(45) NOT NULL,
  `isLike` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`like_num`),
  INDEX `board_num_idx` (`like_board_num` ASC) VISIBLE,
  INDEX `user_email_idx` (`like_user_email` ASC) VISIBLE,
  CONSTRAINT `like_board_num`
    FOREIGN KEY (`like_board_num`)
    REFERENCES `portfolio`.`board` (`board_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `like_user_email`
    FOREIGN KEY (`like_user_email`)
    REFERENCES `portfolio`.`user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`file` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`file` (
  `file_num` INT NOT NULL AUTO_INCREMENT,
  `file_board_num` INT NOT NULL,
  `isMainImg` VARCHAR(1) NOT NULL DEFAULT 'N',
  `file_title` VARCHAR(255) NOT NULL,
  `display` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`file_num`),
  INDEX `board_num_idx` (`file_board_num` ASC) VISIBLE,
  CONSTRAINT `file_board_num`
    FOREIGN KEY (`file_board_num`)
    REFERENCES `portfolio`.`board` (`board_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`comment` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`comment` (
  `comment_num` INT NOT NULL AUTO_INCREMENT,
  `comment_board_num` INT NOT NULL,
  `comment_user_email` VARCHAR(45) NOT NULL,
  `comment_contents` LONGTEXT NOT NULL,
  `registrationDate` DATETIME NOT NULL,
  `display` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`comment_num`),
  INDEX `board_num_idx` (`comment_board_num` ASC) VISIBLE,
  INDEX `user_email_idx` (`comment_user_email` ASC) VISIBLE,
  CONSTRAINT `comment_board_num`
    FOREIGN KEY (`comment_board_num`)
    REFERENCES `portfolio`.`board` (`board_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_user_email`
    FOREIGN KEY (`comment_user_email`)
    REFERENCES `portfolio`.`user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`commentVS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`commentVS` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`commentVS` (
  `commentVS_num` INT NOT NULL AUTO_INCREMENT,
  `commentVS_comment_num` INT NOT NULL,
  `commentVS_user_email` VARCHAR(45) NOT NULL,
  `yORn` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`commentVS_num`),
  INDEX `comment_num_idx` (`commentVS_comment_num` ASC) VISIBLE,
  INDEX `user_email_idx` (`commentVS_user_email` ASC) VISIBLE,
  CONSTRAINT `commentVS_comment_num`
    FOREIGN KEY (`commentVS_comment_num`)
    REFERENCES `portfolio`.`comment` (`comment_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commentVS_user_email`
    FOREIGN KEY (`commentVS_user_email`)
    REFERENCES `portfolio`.`user` (`user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `portfolio` ;

-- -----------------------------------------------------
-- Placeholder table for view `portfolio`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `portfolio`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`view1`;
DROP VIEW IF EXISTS `portfolio`.`view1` ;
USE `portfolio`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
