-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 10:08:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`user` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`user` (
  `userEmail` VARCHAR(45) NOT NULL,
  `userType` VARCHAR(45) NOT NULL DEFAULT 'USER',
  `userName` VARCHAR(45) NOT NULL,
  `userPw` VARCHAR(255) NOT NULL,
  `userPhone` VARCHAR(45) NULL,
  `userGender` VARCHAR(1) NULL DEFAULT 'M',
  `userBirth` DATETIME NULL,
  `confirmFile` VARCHAR(255) NULL,
  `writeBoardCount` INT NULL DEFAULT 0,
  `writeCommentCount` INT NULL DEFAULT 0,
  `likesBoardCount` INT NULL DEFAULT 0,
  `isMember` VARCHAR(1) NULL DEFAULT 'Y',
  PRIMARY KEY (`userEmail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`field` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`field` (
  `fieldNum` INT NOT NULL AUTO_INCREMENT,
  `fieldTitle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fieldNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`inquiry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`inquiry` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`inquiry` (
  `inquiryNum` INT NOT NULL AUTO_INCREMENT,
  `inquiryTitle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`inquiryNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`confirm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`confirm` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`confirm` (
  `confirmNum` INT NOT NULL AUTO_INCREMENT,
  `confirmUserEmail` VARCHAR(45) NOT NULL,
  `sendingTime` DATETIME NOT NULL,
  `isConfirm` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `sendingNum` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`confirmNum`),
  INDEX `user_email_idx` (`confirmUserEmail` ASC) VISIBLE,
  CONSTRAINT `comfirmUserEmail`
    FOREIGN KEY (`confirmUserEmail`)
    REFERENCES `portfolio`.`user` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`board` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`board` (
  `boardNum` INT NOT NULL AUTO_INCREMENT,
  `boardUserEmail` VARCHAR(45) NOT NULL,
  `boardType` VARCHAR(45) NOT NULL,
  `boardTitle` VARCHAR(100) NOT NULL,
  `boardContents` LONGTEXT NOT NULL,
  `registrationDate` DATETIME NOT NULL DEFAULT now(),
  `commentsCount` INT NOT NULL DEFAULT 0,
  `viewsCount` INT NOT NULL DEFAULT 0,
  `likesCount` INT NOT NULL DEFAULT 0,
  `display` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `boardSubtype` VARCHAR(45) NOT NULL,
  `answer` VARCHAR(1) NULL,
  `boardFieldNum` INT NULL,
  `boardInquiryNum` INT NULL,
  PRIMARY KEY (`boardNum`),
  INDEX `user_email_idx` (`boardUserEmail` ASC) VISIBLE,
  INDEX `field_num_idx` (`boardFieldNum` ASC) VISIBLE,
  INDEX `inquiry_num_idx` (`boardInquiryNum` ASC) VISIBLE,
  CONSTRAINT `boardUserEmail`
    FOREIGN KEY (`boardUserEmail`)
    REFERENCES `portfolio`.`user` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `boardFieldNum`
    FOREIGN KEY (`boardFieldNum`)
    REFERENCES `portfolio`.`field` (`fieldNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `boardInquiryNum`
    FOREIGN KEY (`boardInquiryNum`)
    REFERENCES `portfolio`.`inquiry` (`inquiryNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`vsType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`vsType` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`vsType` (
  `vsTypeNum` INT NOT NULL AUTO_INCREMENT,
  `vsTypeBoardNum` INT NOT NULL,
  `yORn` VARCHAR(1) NOT NULL,
  `vsContents` VARCHAR(100) NOT NULL DEFAULT ' ',
  `deadline` DATETIME NOT NULL,
  PRIMARY KEY (`vsTypeNum`),
  INDEX `board_num_idx` (`vsTypeBoardNum` ASC) VISIBLE,
  CONSTRAINT `vsTypeBoardNum`
    FOREIGN KEY (`vsTypeBoardNum`)
    REFERENCES `portfolio`.`board` (`boardNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`surveyType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`surveyType` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`surveyType` (
  `surveyTypeNum` INT NOT NULL AUTO_INCREMENT,
  `surveyTypeBoardNum` INT NOT NULL,
  `questionType` VARCHAR(45) NOT NULL,
  `isEssential` VARCHAR(1) NOT NULL,
  `surveyContents` VARCHAR(100) NOT NULL,
  `deadline` DATETIME NOT NULL,
  `depth` INT NOT NULL,
  `parentsQ` INT NOT NULL,
  PRIMARY KEY (`surveyTypeNum`),
  INDEX `board_num_idx` (`surveyTypeBoardNum` ASC) VISIBLE,
  CONSTRAINT `surveyBoardNum`
    FOREIGN KEY (`surveyTypeBoardNum`)
    REFERENCES `portfolio`.`board` (`boardNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`participation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`participation` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`participation` (
  `participationNum` INT NOT NULL AUTO_INCREMENT,
  `participationUserEmail` VARCHAR(45) NOT NULL,
  `boardSubtype` VARCHAR(45) NOT NULL,
  `participationVsTypeNum` INT NULL DEFAULT 0,
  `participationSurveyTypeNum` INT NULL DEFAULT 0,
  PRIMARY KEY (`participationNum`),
  INDEX `user_email_idx` (`participationUserEmail` ASC) VISIBLE,
  INDEX `vsType_num_idx` (`participationVsTypeNum` ASC) VISIBLE,
  INDEX `surveyType_num_idx` (`participationSurveyTypeNum` ASC) VISIBLE,
  CONSTRAINT `participationUserEmail`
    FOREIGN KEY (`participationUserEmail`)
    REFERENCES `portfolio`.`user` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participationVsTypeNum`
    FOREIGN KEY (`participationVsTypeNum`)
    REFERENCES `portfolio`.`vsType` (`vsTypeNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participationSurveyTypeNum`
    FOREIGN KEY (`participationSurveyTypeNum`)
    REFERENCES `portfolio`.`surveyType` (`surveyTypeNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`like` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`like` (
  `likeNum` INT NOT NULL AUTO_INCREMENT,
  `likeBoardNum` INT NOT NULL,
  `likeUserEmail` VARCHAR(45) NOT NULL,
  `isLike` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`likeNum`),
  INDEX `board_num_idx` (`likeBoardNum` ASC) VISIBLE,
  INDEX `user_email_idx` (`likeUserEmail` ASC) VISIBLE,
  CONSTRAINT `likeBoardNum`
    FOREIGN KEY (`likeBoardNum`)
    REFERENCES `portfolio`.`board` (`boardNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `likeUserEmail`
    FOREIGN KEY (`likeUserEmail`)
    REFERENCES `portfolio`.`user` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`file` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`file` (
  `fileNum` INT NOT NULL AUTO_INCREMENT,
  `fileBoardNum` INT NOT NULL,
  `isMainImg` VARCHAR(1) NOT NULL DEFAULT 'N',
  `fileTitle` VARCHAR(255) NOT NULL,
  `display` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`fileNum`),
  INDEX `board_num_idx` (`fileBoardNum` ASC) VISIBLE,
  CONSTRAINT `fileBoardNum`
    FOREIGN KEY (`fileBoardNum`)
    REFERENCES `portfolio`.`board` (`boardNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`comment` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`comment` (
  `commentNum` INT NOT NULL AUTO_INCREMENT,
  `commentBoardNum` INT NOT NULL,
  `commentUserEmail` VARCHAR(45) NOT NULL,
  `commentContents` LONGTEXT NOT NULL,
  `registrationDate` DATETIME NOT NULL,
  `display` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`commentNum`),
  INDEX `board_num_idx` (`commentBoardNum` ASC) VISIBLE,
  INDEX `user_email_idx` (`commentUserEmail` ASC) VISIBLE,
  CONSTRAINT `commentBoardNum`
    FOREIGN KEY (`commentBoardNum`)
    REFERENCES `portfolio`.`board` (`boardNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commentUserEmail`
    FOREIGN KEY (`commentUserEmail`)
    REFERENCES `portfolio`.`user` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`commentVS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`commentVS` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`commentVS` (
  `commentVSNum` INT NOT NULL AUTO_INCREMENT,
  `commentVSCommentNum` INT NOT NULL,
  `commentVSUserEmail` VARCHAR(45) NOT NULL,
  `yORn` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`commentVSNum`),
  INDEX `comment_num_idx` (`commentVSCommentNum` ASC) VISIBLE,
  INDEX `user_email_idx` (`commentVSUserEmail` ASC) VISIBLE,
  CONSTRAINT `commentVSCommentNum`
    FOREIGN KEY (`commentVSCommentNum`)
    REFERENCES `portfolio`.`comment` (`commentNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commentVSUserEmail`
    FOREIGN KEY (`commentVSUserEmail`)
    REFERENCES `portfolio`.`user` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `portfolio` ;

-- -----------------------------------------------------
-- Placeholder table for view `portfolio`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `portfolio`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`view1`;
DROP VIEW IF EXISTS `portfolio`.`view1` ;
USE `portfolio`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
